#SQL Server

#spring.datasource.url=jdbc:sqlserver://eln.database.windows.net;DatabaseName=ELN-Latest;instance=SQLSERVER;encrypt=true;TrustServerCertificate=true;
spring.datasource.url=jdbc:sqlserver://172.16.17.243;DatabaseName=DB_Testing_eLN_1;instance=SQLSERVER;encrypt=true;TrustServerCertificate=true;
#spring.datasource.url=jdbc:sqlserver://172.16.17.243;DatabaseName=DB_eLN_Dev;instance=SQLSERVER;encrypt=true;TrustServerCertificate=true;
#spring.datasource.url=jdbc:sqlserver://172.16.17.243;DatabaseName=DB_eLN_Prod;instance=SQLSERVER;encrypt=true;TrustServerCertificate=true;
spring.datasource.username=eLN
spring.datasource.password=Eln@12345
#spring.datasource.username=dbo.admin
#spring.datasource.password=Eln@#123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

application-description=@project.description@
application-version=@project.version@
logging.level.org.springframework.boot.autoconfigure=ERROR

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=learning@ectdglobal.com
spring.mail.password=eC!d@958
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# JWT Properties
# Secret key for signing JWTs (keep it strong & private)
jwt.secret=7f4e8c92b1a6d3f0e5c9a2d8b7f1e6c3a9d4b0f8e7c2a1d6b3f9e0c8d5a7b2f1
# Expiration time in milliseconds (e.g. 1 hour)
jwt.expiration=900000
# Refresh token expiration in milliseconds (optional, e.g. 7 days)
jwt.refreshExpiration=604800000
# Token prefix (usually "Bearer ")
jwt.token.prefix=Bearer
# Header where token will be sent
jwt.header=Authorization


file-path=uploads
