get.audit.logs = SELECT ID, USER_NAME, ACTION, CREATED_DATE, EVENT_TYPE, MODULE_SECTION, IP_ADDRESS FROM AUDIT_TRAIL ORDER BY CREATED_DATE DESC
create.audit.logs =  INSERT INTO AUDIT_TRAIL (USER_ID, USER_NAME, ACTION, CREATED_DATE, EVENT_TYPE, MODULE_SECTION, IP_ADDRESS)VALUES (:userId, :userName, :action, :createdDate, :eventType, :moduleSection, :ipAddress)
get.audit.logs.by.userid = SELECT * FROM AUDIT_TRAIL WHERE USER_ID = ? ORDER BY CREATED_DATE DESC
