
#SQL Query for retrieving all control panels with active status
#getControlPanelList=SELECT  USERS_LIMIT, NUMBER_OF_USERS, LICENCE_START_DATE, LICENCE_EXPIRY_DATE  FROM  CONTROL_PANEL;

createControlPanel=INSERT INTO CONTROL_PANEL (USERS_LIMIT,  LICENCE_START_DATE, LICENCE_EXPIRY_DATE) VALUES (:usersLimit,  :licenceStartDate, :licenceExpiryDate);


# SQL Query for updating a control panel
updateControlPanel=UPDATE CONTROL_PANEL SET USERS_LIMIT = :usersLimit,  LICENCE_START_DATE = :licenceStartDate, LICENCE_EXPIRY_DATE = :licenceExpiryDate where CP_ID=1;

#get control panel
getControlPanel=SELECT  TOP 1  USERS_LIMIT,  LICENCE_START_DATE, LICENCE_EXPIRY_DATE  FROM  CONTROL_PANEL ORDER BY [CP_ID] DESC ;

#get no.of users
getNumberOfUsers= SELECT COUNT(USER_ID) FROM USERS_DETAILS WHERE STATUS != 'Inactive' AND ROLE_ID != 5;
