/*
 * Created on 2022-10-02 ( Date ISO 2022-10-02 - Time 11:20:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/
package com.ectd.global.eln.services;

import java.util.List;

import com.ectd.global.eln.dto.UsersDetailsDto;
import com.ectd.global.eln.request.UsersDetailsRequest;

public interface UsersDetailsService {

	UsersDetailsDto getUsersDetailsById(Integer usersDetailsId);

	List<UsersDetailsDto> getUsersDetails();

	Integer createUsersDetails(UsersDetailsRequest usersDetailsRequest);

	Integer updateUsersDetails(UsersDetailsRequest usersDetailsRequest);

	Integer deleteUsersDetails(Integer usersDetailsId);
	
}
